version: "3"

services:
  install:
    image: mhart/alpine-node:10.15
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm i
    networks:
      - nyx

  build:
    image: wodby/node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run build
    networks:
      - nyx

  lint:
    image: wodby/node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run lint
    networks:
      - nyx

  e2e:
    image: wodby/node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run test:e2e
    networks:
      - nyx

  e2e_open:
    image: wodby/node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run test:e2e:open
    networks:
      - nyx

  unit:
    image: wodby/node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run test:unit
    networks:
      - nyx

  unit_snap:
    image: wodby/node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run test:unit:updt:snap
    networks:
      - nyx

  unit_single:
    image: wodby/node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run test:unit:single $FILE_MATCH
    networks:
      - nyx

networks:
  nyx:
    external: true